version: "3.4"
services:

  bot:
    container_name: rag_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    command: 
      python3 /app/bot/get_bot.py
    volumes:
      - logs:/app/logs/
      - user_db:/user_db/

volumes:
  logs:
  user_db: